### ISSUE TITLE
youtube-dl is dead so no longer working

### ISSUE THREAD

**Issue by Felzow47** [fixinPost/youtube-to-resolve-Windows#1]
![image](https://github.com/fixinPost/youtube-to-resolve-Windows/assets/49567056/90f7baa8-ed17-4c6b-bdc5-ff3108fdf54d)

**Comment by madMonKAY** [comment]
I forked the project and made it work with yt-dlp which is the current active fork of youtube-dl.

https://github.com/madMonKAY/youtube-to-resolve-Windows

**Comment by Felzow47** [comment]
> I forked the project and made it work with yt-dlp which is the current active fork of youtube-dl.
> 
> https://github.com/madMonKAY/youtube-to-resolve-Windows

AWESOME !! Thx a lot ! 
I test that when I get home!
